### ISSUE TITLE
Deprecation Warnings

### ISSUE THREAD

**Issue by WoLfulus** [konsumer/grpc-dynamic-gateway#13]
How hard would it be to update the grpc load functions?

I'm getting a lot of 

```(node:1156) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead```

But seems like `load` doesn't behave like `loadPackageDefinition` because when I tried making a quick patch

```
grpc.load = function(options) {
	return grpc.loadPackageDefinition(
		loader.loadSync(options.file, {
			keepCase: true,
			includeDirs: [options.root],
		})
	);
};
```

Enumerations stopped serializing as string and turned into numbers in the response's json object

**Comment by konsumer** [comment]
would you mind posting the project that you tried with?  I am thinking maybe this needs an overhaul, and I'd like to have some test cases for the stuff you've tried so far.

**Comment by WoLfulus** [comment]
I'm using the express example on README.

The proto file:

```proto
syntax = "proto3";

package Services;

service Test {
  rpc Method(Method.Request) returns (Method.Reply) {
    option (google.api.http) = {
      post: "/test/method"
      body: "*"
    };
  }
}

message Method {
  enum Status {
    SUCCESS = 0;
    ERROR = 1;
  }

  message Request {
    string value = 1
  }

  message Reply {
    Method.Status status = 1;
  }
}
```

In the `Test.Method` implementation, if I `return { status: 0 };` the response gets to the client as `{"status": "SUCCESS"}` but I do get deprecation warnings.

After applying the "patch", the deprecation warning is gone but the response is sent as `{"status": 1}`

**Comment by konsumer** [comment]
I think this is resolved, but feel free to add more comments if not. Closing for now.
