### ISSUE TITLE
No published Docker build

### ISSUE THREAD

**Issue by yinzara** [konsumer/grpc-dynamic-gateway#28]
Though there is a Dockerfile, the Travis CI build does not actually push to Docker Hub so the image is not available as is shown in the readme 

This can be rectified by creating a konsumer DockerHub account (if you don't already have one), updating TravisCI with the dockerhub credentials, and updating the travis build to call Docker build and push on the master branch.

**Comment by konsumer** [comment]
It is published [here](https://hub.docker.com/r/konsumer/grpc-gateway). Has been for 2 years. That said, I'm willing to accept a PR set it up in CI, so it's automatic (and updated more often.) I don't really use it too much, myself. (I use the go-based gateway in docker, and the node-based gateway in my own node stuff, without a seperate docker.) It does remind me to publish to docker-hub, again, though.

**Comment by konsumer** [comment]
Oh wait! Actually that is a modified go-version that uses a similar technique. You are correct, I never published it. I will do that now.

**Comment by konsumer** [comment]
Published [here](https://hub.docker.com/r/konsumer/grpc-dynamic-gateway). Again, happy to accept a PR for auto-CI publishes. I looked around for a tutorial, and found a few that seemed pretty complicated, so if you know of a simple way to set it up, that would be best.

**Comment by konsumer** [comment]
Actually, just added it to travis config. Feel free to PR for improvements.
