### ISSUE TITLE
if package name has a dot. 

### ISSUE THREAD

**Issue by seamys** [konsumer/grpc-dynamic-gateway#7]
Hi, if package name has a dot.
![image](https://user-images.githubusercontent.com/7090368/37747853-1eb4cd22-2dbc-11e8-8f70-5139effb6e5d.png)

This part of the codes will not work
https://github.com/konsumer/grpc-dynamic-gateway/blob/93fa8e99a8aa98f26e70d92db11096040226808e/index.js#L44

**Comment by seamys** [comment]
same issue with https://github.com/konsumer/grpc-dynamic-gateway/issues/3

**Comment by konsumer** [comment]
I am going to dig back into this. Looks like [this issue](https://github.com/konsumer/grpcnode/issues/2) might be related.
